apiVersion: v2
name: ferment
description: A starter chart for helmetica transmuter charts

# Transmuter charts are always application charts
type: application

version: 0.0.18

appVersion: "1.16.0"

# TODO: once we have a lib
dependencies: []
